version: '3'

services:
  database:
    image: postgres:13.4-buster
    ports:
      - 5431:5432
    # volumes:
    #   - db:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./@types:/app/@types
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - database

volumes:
  db:
