version: '3'

services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    environment:
      POSTGRES_USER: user_demo
      POSTGRES_PASSWORD: pg_strong_password
      PGDATA: /data/postgres
      POSTGRES_DB: demo_db

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./@types:/app/@types
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://user_demo:pg_strong_password@postgres-db:5432/demo_db

volumes:
  db: {}
